# Generated by Django 4.2.1 on 2024-04-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_alter_producto_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='sin categoria', max_length=100),
        ),
    ]
