# Generated by Django 4.2.1 on 2024-04-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='email_contacto',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
