# Generated by Django 4.2.1 on 2024-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_proveedor_email_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
