# Generated by Django 4.2.1 on 2024-04-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_proveedor_tipo_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='email_contacto',
            new_name='mail_contacto',
        ),
    ]
