# Generated by Django 4.2.1 on 2024-04-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0008_rename_email_contacto_proveedor_mail_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
