# Generated by Django 4.2.1 on 2024-04-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_alter_producto_options_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
